[package]
name = "mqtt-smart-devices"
version = "0.1.0"
authors = ["sadfsdf <mamogaaa@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.0"
wake-on-lan = "0.2.0"